### ISSUE TITLE
Often fail to reset the environment 

### ISSUE THREAD

**Issue by dgjun32** [ServiceNow/BrowserGym#103]
Hi, I am using browser gym environment for webarena evaluation. 
Following the guideline in webarena repo (link below),

https://github.com/web-arena-x/webarena/blob/main/environment_docker/README.md#environment-reset

I setup the aws instance to host the webarena environment. However, I am often faced with playwright error as shown in the screenshot. It seems there is no problem in AWS instance, but evaluation often stops due to randomly failing to reset environment.

![image](https://github.com/user-attachments/assets/e3a16bb7-7e44-4ce9-9fa9-437f90ee5627)

Do you have any experience with such situation? 

Thank you.

**Comment by dgjun32** [comment]
We are also considering to demonstrate our method in WorkArena benchmark rather than WebArena (due to instability & faulty reward metric in webarena).

Is there any similar issue in the workarena environment?

**Comment by gasse** [comment]
WorkArena should be easier to setup and is more robust in our experience. Feel free to give it a try 🙂
