### ISSUE TITLE
GPT-4o agent code

### ISSUE THREAD

**Issue by Serega6678** [ServiceNow/BrowserGym#104]
In your paper you mention the existence of GPT-4o-powered text-only agent (no vision) that scores 42.7 ±1.5 on work arena.
Is this agent currently open sourced?
Is this the one?
https://github.com/ServiceNow/BrowserGym/tree/main/demo_agent/agents/basic

Thank you

**Comment by gasse** [comment]
Hi @Serega6678 , you will find the agents we used in the paper in a separate repo: https://github.com/servicenow/agentlab

**Comment by Serega6678** [comment]
Thank you very much for your work and for the fast response!

**Comment by gasse** [comment]
You're welcome :)
