### ISSUE TITLE
Configuration for Webarena

### ISSUE THREAD

**Issue by gimme1dollar** [ServiceNow/BrowserGym#105]
Thanks for a very nice work! I'm trying to reproduce your results on the WebArena benchmark. However, table 1 in the main text only specifies agent configuration on MiniWob and WorkArena. Could you provide a detailed configuration for the agent in WebArena as well?

It would be very appreciated if you could specify the values of each flag (https://github.com/ServiceNow/BrowserGym/blob/6899cdff14aae88cf01e86eb78058555c6e73d5b/demo_agent/agents/legacy/dynamic_prompting.py#L29).

**Comment by ThibaultLSDC** [comment]
Hi, thanks for your interest !
For WebArena, we used the WorkArena configuration. We did not perform a specific tuning for WebArena as running on it can sometimes be a bit tedious.
Hope this helps !

**Comment by gimme1dollar** [comment]
Thanks for the reply!
