### ISSUE TITLE
Static text elements aria descriptiors

### ISSUE THREAD

**Issue by suhamansuri22** [ServiceNow/BrowserGym#109]
In the javascript file that marks elements, they say to store custom data in the aria role description property as it is accessible in the axtree. I am trying to assign that property to specific elements in my code such as static text elements from generic/div html code that represent dropdowns. When i try to set the aria role description property for these static text elements, it doesnt seem to be properly set. is there a reason why?

**Comment by imenelydiaker** [comment]
Hey @suhamansuri22,

I tested it on my end on `miniwob.order-food` task, it seems to be working correctly, `aria-roledescription` values are added to axtree and dom:

**Code:**
![image](https://github.com/user-attachments/assets/07448b31-6f21-426a-a219-a9de851d09ca)

**AXTree:**
![image](https://github.com/user-attachments/assets/a43f1d24-7e49-4fe3-ac6b-9d70a7036ba8)

**DOM:**
![image](https://github.com/user-attachments/assets/a6f40e46-58cd-40f2-9f34-81ca6bd80884)

Note that `StaticText` won't contain any attributes as it only  contains the text value that was present in the element with roles generic, heading, radio, etc. The attributes are added to the element containing the text. See example here where I added an `aria-label` for `div` and `h2`:

![image](https://github.com/user-attachments/assets/6b07f576-83c0-4121-b69b-47d32b80ded4)

Hope this answers your question.
