### ISSUE TITLE
Problem with interaction between UI assistant and opened page

### ISSUE THREAD

**Issue by Key-J** [ServiceNow/BrowserGym#13]
After running `python3 run_demo.py --task_name openended --start_url https://wikipedia.org"`,
the ui-assistant attempts to interact with the opened page but the page does not have a response. Below is a video showing the actions ui-assistant took when I asked "when did Roman Empire fall?" in the chatbox.

https://github.com/ServiceNow/BrowserGym/assets/123200817/e3c097bf-e684-4e9b-ade1-8b6ccf379cd2

In the beginning of the video, before the prompt is entered into the chatbox, we can already see that the UI-assistant tries to click the search box, but there are no response from the page. 

I already made sure that code [86] indeed represents the searchbox by adding`print(f"instructions:{self.obs._prompt}")` within `__init__()` of `class MainPrompt(Shrinkable)` within `dynamic_prompting.py`) and running the instruction at the top of the post.

After I entered the prompt, the UI-assistant correctly processed the input and also have the correct thought process, but the terminal shows that there are errors when the UI-assistant attempts to fill the search bar. I also tried this with the default webpage of google home page, same issue arises.

Any clues on how to fix this issue?

**Comment by gasse** [comment]
Hi @Key-J , thanks for reaching out! There was a bug indeed, just fixed it. Can you confirm it works now?

**Comment by Key-J** [comment]
It works now, thank you so much!!
