### ISSUE TITLE
Issue running async agent due to the event loop being stuck indefinitely. 

### ISSUE THREAD

**Issue by rutgercap** [ServiceNow/BrowserGym#134]
Hi,

I'm trying to use browsergym to evaluate my agent. The problem I am facing is that my agent is async and browsergym seems to occupy the eventloop. I tried a bunch of things to run my agent through asyncio, but it seems like browsergym already occupies the eventloop and I can't seem to add anything to the eventloop without it waiting indefinitely. I have tried a bunch of different ways to run async functions from a sync context, but none seem to work in the setup given below.

Here is a minimal reproduction:
```
import asyncio
import random
from time import sleep
from typing import Sequence
import gymnasium as gym
from browsergym.workarena import ALL_WORKARENA_TASKS


class BrowserGymAdapter:
    async def _async_get_action(self, obs: dict) -> Sequence[str]:
        raise NotImplementedError("Does not matter")

    def get_action(self, obs: dict) -> Sequence[str]:
        event_loop = asyncio.get_event_loop()
        result = asyncio.ensure_future(self._async_get_action(obs), loop=event_loop)
        while not result.done():
            print("Waiting for result")
            sleep(0.1)
        return result.result()
    
    ## or

    def get_action_2(self, obs: dict) -> Sequence[str]:
        return asyncio.run(self._async_get_action(obs))


random.shuffle(ALL_WORKARENA_TASKS)
for task in ALL_WORKARENA_TASKS:
    env = gym.make("browsergym/workarena.servicenow.order-ipad-pro")
    obs, info = env.reset()
    agent = BrowserGymAdapter()
    action = agent.get_action(obs)
    # action = agent.get_action_2(obs)

```

When ran with get_action_2, the error is:

```
RuntimeError: asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine 'TwinBrowserGymAdapter._async_get_action' was never awaited
```

Does browsergym somehow occupy the eventloop indefinitely? Have you encountered this before? Are there solutions that I'm not thinking of? 

Any help is welcome. 
Thanks a lot!

**Comment by gasse** [comment]
Hi @rutgercap , we decided to go with playwright in sync mode a while ago, which might be the source of your problem. Unfortunately it will require substantial efforts to switch all of BrowserGym's code base back to async mode. Glad you found a workaround! This is good to know.

**Comment by rutgercap** [comment]
As you should! 
Python is not made for async...
