### ISSUE TITLE
Better Error messages when receiving timeouts

### ISSUE THREAD

**Issue by recursix** [ServiceNow/BrowserGym#140]
Timout errors is by far the #1 error message from browsergym.
The agent would benefit from having more info about the cause of the timeout.

With some code on the browsergym side, we could possibly extract some useful information.

* The bid doesn't exist on the page
* The bid exists but is not clickable or not visible
* The bid existed on the previous page, but the current status of the page just changed and it doesn't exist
* Any other ideas on what could cause those timeouts?

The timeout error message is also often long, perhaps it could be reduced in size.

**Comment by recursix** [comment]
Example of a not so useful timeout:

It tries to fill a textbox, but for some reason, it doesn't work. In this task you have to click on the box and wait for the menu to appear. Would there be a way to extract further properties of this element to give insights about what's going on?

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/e4eed83b-8769-4d9d-8581-fc580a3347b5">

AXTree:
RootWebArea 'Book Flight Task', focused
	[17] heading 'Book Your One-Way Flight', visible
	[19] textbox 'From:' value='Latrobe, PA', clickable, visible
		StaticText 'Latrobe, PA'
	[21] textbox 'To:' value='Elmira, NY', clickable, visible, focused
		StaticText 'Elmira, NY'
	StaticText 'Departure Date'
	[25] textbox '', clickable, visible
	[27] button 'Search', clickable, visible
	[30] status '', live='assertive', atomic, relevant='additions'
		StaticText '1 result is available, use up and down arrow keys to navigate.'
	[31] list 'Elmira, NY (ELM)', clickable, visible
		[37] listitem '', visible
			ListMarker ''
				image ''
			StaticText 'Elmira, NY (ELM)'
	[32] status '', live='assertive', atomic, relevant='additions'
		StaticText '1 result is available, use up and down arrow keys to navigate.'

**Comment by recursix** [comment]
ok, after discussion it seems like these cases are already handled

**Comment by gasse** [comment]
Closing stale issue. Feel free to reopen @recursix if you find a specific use case
