### ISSUE TITLE
miniwob book-flight, search button doesn't seem to work.

### ISSUE THREAD

**Issue by recursix** [ServiceNow/BrowserGym#156]
The agent fill the fields as expected and then click search `click('27')`, but nothing happens. It does that for all the seeds. 

AXTree:
RootWebArea 'Book Flight Task', focused
	[17] heading 'Book Your One-Way Flight', visible
	[19] textbox 'From:' value='PPV', clickable, visible
		StaticText 'PPV'
	[21] textbox 'To:' value='DDC', clickable, visible
		StaticText 'DDC'
	StaticText 'Departure Date'
	[25] textbox '' value='11/21/2016', clickable, visible
		StaticText '11/21/2016'
	[27] button 'Search', clickable, visible
	[30] status '', live='assertive', atomic, relevant='additions'
		StaticText '1 result is available, use up and down arrow keys to navigate.'
	[32] status '', live='assertive', atomic, relevant='additions'
		StaticText '1 result is available, use up and down arrow keys to navigate.'

![image](https://github.com/user-attachments/assets/c8a4594a-779f-4e64-afce-4cac17e5543b)

**Comment by gasse** [comment]
I tried to reproduce on my side, I confirm the click does not work. We need to investigate

**Comment by gasse** [comment]
It seems to be normal behaviour (on my side at least). When the agent first clicks on search, the input boxes turn red.
![Screenshot 2024-09-26 at 9 47 50 AM](https://github.com/user-attachments/assets/a5261155-91d6-47f4-b206-db087411c38f)

**Comment by gasse** [comment]
I reproduced by hand, you have to pick the value of these fields by clicking on the autocomplete suggestions to succeed. If you just copy-paste the values in the field but don't click on the matching suggestion, you fail. Seems like a poorly designed UI, but it's part of the challenge. Not a bug.
@recursix can you try on your side (https://miniwob.farama.org/demos/miniwob/book-flight.html) and confirm it's not a bug?

**Comment by recursix** [comment]
Ohhh wow. Thanks! It's probably just that. If I come across it, I'll verify that the screenshot has the red lines at least.
