### ISSUE TITLE
Benchmark Server objects

### ISSUE THREAD

**Issue by recursix** [ServiceNow/BrowserGym#175]
Make a class that encapsulates the complexity of servers as much as possible and provides a useful error message to users when needed.

* WorkArena:
  * if env vars are not define, it refers to the readme on how to set it up
  * if the vars are there it test if the server is hybernating or available. if it's hybernating, eventually, we can probably make a script to revive it (if it's posssible).
* MiniWob:
  * If vars are not setup, perhaps with should set it up automatically
* WebArena:
  * If not set up, refers to readme on how to set it up
  * Verify if server is responding. 
Make sure the instance is fresh if not, it reset it.

```python
class BenchmarkServer:
    def prepare(self):
        """Verify that the server is wll configured and running.
        
        If not, try to fix it or raise a meaningful exception pointing to the appropriate readme.

        If server needs to reset call it here.
        """
        pass

    def _reset(self):
        """Reset the server state to the initial state before evaluating an agent.
        
        This method is called before each benchmark run.
        """
        pass

```

**Comment by gasse** [comment]
Done with #204
