### ISSUE TITLE
environment variable for site URLs used in eval are different from those used by browsergym

### ISSUE THREAD

**Issue by xhluca** [ServiceNow/BrowserGym#265]
Browsergym uses `WA_<name>` environment variable, whereas the ones used by webarena are directly the names, e.g.:

```
export WA_SHOPPING="$BASE_URL:7770/"
export WA_SHOPPING_ADMIN="$BASE_URL:7780/admin"
export WA_REDDIT="$BASE_URL:9999"
export WA_GITLAB="$BASE_URL:8023"
export WA_WIKIPEDIA="$BASE_URL:8888/wikipedia_en_all_maxi_2022-05/A/User:The_other_Kiwix_guy/Landing"
export WA_MAP="$BASE_URL:3000"
export WA_HOMEPAGE="$BASE_URL:4399"
```

And the ones used by the original webarena, which is used for eval:
```
export SHOPPING="$BASE_URL:7770/"
export SHOPPING_ADMIN="$BASE_URL:7780/admin"
export REDDIT="$BASE_URL:9999"
export GITLAB="$BASE_URL:8023"
export WIKIPEDIA="$BASE_URL:8888/wikipedia_en_all_maxi_2022-05/A/User:The_other_Kiwix_guy/Landing"
export MAP="$BASE_URL:3000"
export HOMEPAGE="$BASE_URL:4399"
```

Here's the specific line: https://github.com/ServiceNow/BrowserGym/blob/4ac018ce5ccd95ee07a4442603c2dabee2901a2a/browsergym/webarena/src/browsergym/webarena/task.py#L64

I think this will create problems with rewards in tasks where the functional evaluator checks for URL match, since it will be "None" for all of those.

---

Related issue: https://github.com/ServiceNow/BrowserGym/issues/243

**Comment by gasse** [comment]
Hi @xhluca . We did this to differentiate the WebArena and VisualWebArena configs, as the original environment variables were clashing. I don't think this will be an issue for the evaluators since all URL patterns (`__GITLAB__`, `__REDDIT__` etc.) in the config are replaced by the actual URLs when a task is instantiated. Feel free to re-open if you still believe this is an issue, but it would be nice if you could provide more evidence for this.

**Comment by xhluca** [comment]
In the line i quoted, we see that the `__PATTERN__` are replaced by the URLs in `self.webarena_instance.urls`. Howeer, `self.webarena_instance.urls` are populated from `webarena`-specific environment variables like `SHOPPING`, `REDDIT`, etc. I believe that if you don't specify them, they will default to `None`, which means that it may affect the evaluation by marking instances where the URL is correct as incorrect, since we never set the webarena-specific env vars.

I might be incorrect though; let me know if it's an issue under your radar.

**Comment by gasse** [comment]
The environment variables are overridden here, before importing webarena
https://github.com/ServiceNow/BrowserGym/blob/main/browsergym/webarena/src/browsergym/webarena/instance.py#L25-L33
