### ISSUE TITLE
`visualwebarena.csv`: eval_types and overall_difficulty are inverted

### ISSUE THREAD

**Issue by xhluca** [ServiceNow/BrowserGym#275]
https://github.com/ServiceNow/BrowserGym/blob/da26a5849d99d9a3169d7b1fde79f909c55c9ba7/browsergym/experiments/src/browsergym/experiments/benchmark/metadata/visualwebarena.csv#L2

In the example above, overall_type is mapped to "url_match" and whereas eval_types is mapped to medium. but it should be the other way around

**Comment by gasse** [comment]
It was inverted indeed, thanks for the catch @xhluca !
(fixed in #278)
