### ISSUE TITLE
Could You Provide the Trajectory Data for the Main Results Table?

### ISSUE THREAD

**Issue by yeonjooooni** [ServiceNow/BrowserGym#276]
Hi, I noticed that the main result table in your paper reports benchmark performance, but I couldn't find the detailed trajectory data used to produce these results. Could you kindly provide the trajectory data for the main result table, or point me to where it might already be available? It would be extremely helpful for my ongoing research and analysis.

<img width="576" alt="스크린샷 2024-11-25 오후 6 49 54" src="https://github.com/user-attachments/assets/7e2ff216-7795-4816-8df6-07f83ab63f12">

**Comment by gasse** [comment]
Hi @yeonjooooni. Unfortunately I don't think we have kept those trace, sorry.
