### ISSUE TITLE
No module named 'browsergym.experiments'

### ISSUE THREAD

**Issue by SashvDave** [ServiceNow/BrowserGym#42]
Trying to run demo agent but receiving the error attached

![Screenshot 2024-05-24 at 12 52 33 PM](https://github.com/ServiceNow/BrowserGym/assets/55955567/2c9acd2c-b2ff-4b0d-b417-ea319cc9a8e4)

Also, separate question--when trying to run the open-ended example, should action be text-based?

**Comment by SashvDave** [comment]
@gasse, sorry forgot to tag you when creating the issue. Thank you for your help

**Comment by imenelydiaker** [comment]
Hey @SashvDave, this should be solved with `pip install browsergym-experiments`.

We should add the dependency in the requirements of `demo_agent`, will open a PR, thank you for reporting this!
