### ISSUE TITLE
Rate Limit Error

### ISSUE THREAD

**Issue by SashvDave** [ServiceNow/BrowserGym#46]
Keeps on running into rate limit issue even after retrying multiple times. Is this something wrong on my end or are there some changes I'm supposed to make?

also, just so I'm understanding the repo correctly, this is like an autonomous web agent? As in, given a prompt, it can search the web with some level of intelligence and depth? Thank you for the help.

<img width="676" alt="Screenshot 2024-05-25 at 9 16 59 AM" src="https://github.com/ServiceNow/BrowserGym/assets/55955567/cf695c69-8406-41fe-ace9-382db524fcec">

**Comment by gasse** [comment]
Hi @SashvDave

1) the rate limit error is most likely on your side. Check your openAI account.

2) it's just a demo agent, but yes
