### ISSUE TITLE
Too Many requests error

### ISSUE THREAD

**Issue by 11PRiyansh** [ServiceNow/BrowserGym#5]
I tried running the Demo agent with Openai api key, but it says "too many requests" with gpt4v and "max token limit reached" with gpt3.5turbo.

Kindly advice, am I missing something? 
Any guide to load any other model will be pretty helpful.

Thanks.

**Comment by gasse** [comment]
Hi @11PRiyansh , thanks for reaching out. This seems like an OpenAI issue, probably your key does not allow API calls. We are currently working on improving our documentation and providing tutorials for developing new agents and environment, so tay tuned.

Closing this issue as it's not BrowserGym-related.
