### ISSUE TITLE
Use kwargs instead of positional args.

### ISSUE THREAD

**Issue by Am1n3e** [ServiceNow/BrowserGym#86]
Using **kwargs (keyword arguments) in Python provides several benefits over using positional arguments. Here are some key reasons:

Flexibility and Readability: Keyword arguments allow the function caller to pass arguments in a way that makes their purpose clear. This enhances readability and makes the code easier to understand and maintain.

```python
def connect_to_db(host, port, user, password):
    pass

# Call with positional arguments
connect_to_db('localhost', 5432, 'admin', 'secret')

# Call with keyword arguments
connect_to_db(host='localhost', port=5432, user='admin', password='secret')
``` 
Extensibility: Adding new parameters to a function signature is easier when using **kwargs. You can add new arguments **without breaking existing calls to the function.**

Forwarding Arguments: If you’re writing a wrapper function that calls another function, **kwargs make it easy to pass along arguments.

```python
def wrapper_function(*args, **kwargs):
    # Do some preprocessing
    result = target_function(*args, **kwargs)
    # Do some postprocessing
    return result
```

For parameters with with no default value we can use:

```python
def my_func(*, arg1, arg2):
   pass

def my_member_func(self, *, arg1, arg2, arg3=None)
   pass
```

The effort to change everything to kwargs is considerable, of course, but can be done iteratively. 
Also, if we agree on this we can have new functionality follow this guideline.

Note that this something LM-eval harness added a while ago since it make refactoring much easier

https://github.com/EleutherAI/lm-evaluation-harness/commit/8ebe36b25f81be9a9cd237156a2037bf750d6189

**Comment by gasse** [comment]
Closing this a won't fix, it would be a nice feature but we don't have bandwidth at the moment
